// 父级公共的页面状态
export const PAGE_STATE_COMMON_MORE = 'PAGE_STATE_COMMON_MORE'

// 页面状态
export const PAGE_STATE_ADD = 'PAGE_STATE_ADD'
export const PAGE_STATE_INDEX = 'PAGE_STATE_INDEX'
export const PAGE_STATE_MORE_WAIT = 'PAGE_STATE_MORE_WAIT'
export const PAGE_STATE_MORE_BEGIN = 'PAGE_STATE_MORE_BEGIN'
export const PAGE_STATE_UPLOAD = 'PAGE_STATE_UPLOAD'

// 页面接收参数
export const PAGE_PARAM_ADD = 'PAGE_PARAM_ADD'
export const PAGE_PARAM_INDEX = 'PAGE_PARAM_INDEX'
export const PAGE_PARAM_MORE_WAIT = 'PAGE_PARAM_MORE_WAIT'
export const PAGE_PARAM_MORE_BEGIN = 'PAGE_PARAM_MORE_BEGIN'
export const PAGE_PARAM_UPLOAD = 'PAGE_PARAM_UPLOAD'

// 页面初始化数据动作
export const PAGE_INIT_DATA_ADD = 'PAGE_INIT_DATA_ADD'
export const PAGE_INIT_DATA_INDEX = 'PAGE_INIT_DATA_INDEX'
export const PAGE_INIT_DATA_MORE_WAIT = 'PAGE_INIT_DATA_MORE_WAIT'
export const PAGE_INIT_DATA_MORE_BEGIN = 'PAGE_INIT_DATA_MORE_BEGIN'
export const PAGE_INIT_DATA_UPLOAD = 'PAGE_INIT_DATA_UPLOAD'

// 页面承诺
export const PAGE_PROMISE_ADD = 'PAGE_PROMISE_ADD'
export const PAGE_PROMISE_INDEX = 'PAGE_PROMISE_INDEX'
export const PAGE_PROMISE_MORE_WAIT = 'PAGE_PROMISE_MORE_WAIT'
export const PAGE_PROMISE_MORE_BEGIN = 'PAGE_PROMISE_MORE_BEGIN'
export const PAGE_PROMISE_UPLOAD = 'PAGE_PROMISE_UPLOAD'

// 页面数据查询
// 回填查询
export const PAGE_QUERY_MORE_ADD = 'PAGE_QUERY_MORE_ADD'

// 挑战大厅列表
export const PAGE_QUERY_LIST_HALL_INDEX = 'PAGE_QUERY_LIST_HALL_INDEX'
export const PAGE_QUERY_LIST_HALL_PAGE_INDEX = 'PAGE_QUERY_LIST_HALL_PAGE_INDEX'
// 我的列表
export const PAGE_QUERY_LIST_MY_INDEX = 'PAGE_QUERY_LIST_MY_INDEX'
export const PAGE_QUERY_LIST_MY_PAGE_INDEX = 'PAGE_QUERY_LIST_MY_PAGE_INDEX'
// 详情
export const PAGE_QUERY_MORE_MORE_WAIT = 'PAGE_QUERY_MORE_MORE_WAIT'

