// 权限函数
// 获取当前用户权限 游客还是用户
export const AUTH_IS_LOGIN = 'AUTH_IS_LOGIN'
// 激活注册页面
export const REGISTER_ACTIVE = 'REGISTER_ACTIVE'
// 注册成功之后的回调
export const REGISTER_SUCCESS_CALLBACK = 'REGISTER_SUCCESS_CALLBACK'
// 注册失败之后的回调
export const REGISTER_FAILURE_CALLBACK = 'REGISTER_FAILURE_CALLBACK'

// 输入文本模块
export const PAGE_STATE_INPUT_CONTENT = 'PAGE_STATE_INPUT_CONTENT'
export const PAGE_PARAM_INPUT_CONTENT = 'PAGE_PARAM_INPUT_CONTENT'
export const PAGE_PARAMPOST_INPUT_CONTENT = 'PAGE_PARAMPOST_INPUT_CONTENT'
export const PAGE_INIT_DATA_INPUT_CONTENT = 'PAGE_INIT_DATA_INPUT_CONTENT'
export const PAGE_PROMISE_INPUT_CONTENT = 'PAGE_PROMISE_INPUT_CONTENT'

// 裁剪图片模块
export const PAGE_STATE_CROP_IMG = 'PAGE_STATE_CROP_IMG'
export const PAGE_PARAM_CROP_IMG = 'PAGE_PARAM_CROP_IMG'
export const PAGE_PARAMPOST_CROP_IMG = 'PAGE_PARAMPOST_CROP_IMG'
export const PAGE_INIT_DATA_CROP_IMG = 'PAGE_INIT_DATA_CROP_IMG'
export const PAGE_PROMISE_CROP_IMG = 'PAGE_PROMISE_CROP_IMG'

// 微信分享内容设置
export const WEIXIN_SHARE_OBJ = 'WEIXIN_SHARE_OBJ'

// 路由记录
// 加入记录
export const ROUTER_MANAGER_PUSH = 'ROUTER_MANAGER_PUSH'
// 退出一个记录
export const ROUTER_MANAGER_POP = 'ROUTER_MANAGER_POP'
// 判断是否返回
export const ROUTER_MANAGER_IS_BACK = 'ROUTER_MANAGER_IS_BACK'

